apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  annotations:
  labels:
    app.kubernetes.io/instance: demo
    app.kubernetes.io/name: demo
    app.kubernetes.io/version: 1.1.0
  name: demo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: demo
      app.kubernetes.io/name: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp:
      labels:
        app.kubernetes.io/instance: demo
        app.kubernetes.io/name: demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - demo
      containers:
        - envFrom:
            - configMapRef:
                name: demo
            - secretRef:
                name: db-credentials-msa
          image: account-id.dkr.ecr.us-east.1.amazonaws.com/repo-name:51 # {"$imagepolicy": "flux-system:example1-dev-policy"}
          imagePullPolicy: IfNotPresent
          name: customer-application-msa
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: demo
      serviceAccountName: demo
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: demo
status: {}
