apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: example1-dev-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: example1-dev
  filterTags:
    pattern: '^(?P<version>[0-9]+)'
    extract: '$version'
  policy:
    numerical:
      order: asc
