---
apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: example2-dev
  namespace: flux-system
spec:
  secretRef:
    name: ecr-credentials
  image: account-id.dkr.ecr.us-east-1.amazonaws.com/example2-repo-name
  interval: 1m0s
